### ISSUE TITLE
Add support for event log rotation

### ISSUE THREAD

**Issue by hvelarde** [plone/plone.recipe.zeoserver#17]
Currently the ZEO server event log grows without limit and that's far from optimal.

We can take ideas from [plone.recipe.zope2instance](https://github.com/plone/plone.recipe.zope2instance/search?utf8=%E2%9C%93&q=event-log-max-size) on how to implement that.

**Comment by hvelarde** [comment]
I just tested with something like this and it works:

```
<eventlog>
  level info
  <logfile>
      path /foo/bar/var/log/zeoserver.log
      format %(asctime)s %(message)s
      max-size 10MB
      old-files 7
    </logfile>
</eventlog>
```

this seems easy to implement.

**Comment by mauritsvanrees** [comment]
I have released plone.recipe.zeoserver 1.3 with this feature.
