### ISSUE TITLE
Run tests via Travis-CI

### ISSUE THREAD

**Issue by icemac** [plone/plone.recipe.zeoserver#20]
This would require to activate the project on Travis-CI (Requires admin permissions on the repos.) and writing a `.travis.yml` (which everyone could do.)

This could help to ease fixing #19.

**Comment by gforcada** [comment]
@icemac travis is enabled: https://travis-ci.org/plone/plone.recipe.zeoserver, would you mind adding the ``.travis.yml``? Thanks!
