### ISSUE TITLE
"ValueError: Attempted relative import in non-package" - In windows

### ISSUE THREAD

**Issue by fazalsulaiman** [plone/plone.recipe.zeoserver#42]
**System Details**
> **OS:** Windows server 2016 data center (64bit)
> **Python version:** 2.7.18 (32bit)
> **plone.recipe.zeoserver version:** 2.0.1
> **zc.buildout:** 2.13.3
> **setuptools:** 44.0.0

Initially when we are installing zeo from buildout, we are getting below error

```
modules\zeo_build\eggs\plone.recipe.zeoserver-2.0.1-py2.7.egg\plone\recipe\zeoserver\recipe.py", 
line 460, in install_win32_scripts
 
      runzeo_filename), runzeo % arguments)
 
  KeyError: 'zodb3_home'
```
> PR created for this issue: https://github.com/plone/plone.recipe.zeoserver/pull/41

Post above PR change zeo installed with no issues, after that while running ZEO as a service, we are getting "ValueError: Attempted relative import in non-package" error

**Error Message from Event Viewer**
```
ZEO_-719346442 (ZEO instance at D:\work\zope4\modules\zeo_build\parts\zeo_server1): Process terminated with exit code 1.
Traceback (most recent call last):
  File "d:\work\zope4\modules\zeo_build\eggs\zeo-5.2.1-py2.7.egg\\ZEO\\runzeo.py", line 399, in <module>
    main()
  File "d:\work\zope4\modules\zeo_build\eggs\zeo-5.2.1-py2.7.egg\\ZEO\\runzeo.py", line 390, in main
    s.main()
  File "d:\work\zope4\modules\zeo_build\eggs\zeo-5.2.1-py2.7.egg\\ZEO\\runzeo.py", line 153, in main
    self.create_server()
  File "d:\work\zope4\modules\zeo_build\eggs\zeo-5.2.1-py2.7.egg\\ZEO\\runzeo.py", line 249, in create_server
    self.server = create_server(self.storages, self.options)
  File "d:\work\zope4\modules\zeo_build\eggs\zeo-5.2.1-py2.7.egg\\ZEO\\runzeo.py", line 343, in create_server
    from .StorageServer import StorageServer
ValueError: Attempted relative import in non-package
```

**Comment by mauritsvanrees** [comment]
@jensens Since you fixed some Windows stuff recently, could you look at this?

For the second part, does the next comment help?
https://github.com/zopefoundation/ZEO/issues/163#issuecomment-670544990
Running buildout should have created a `bin/zeoserver` (or maybe `bin/zeo`) script. Maybe `.exe` behind it, or something like that. Can you try running that command instead?

**Comment by fazalsulaiman** [comment]
Issue fixed in https://github.com/plone/plone.recipe.zeoserver/pull/43
