### ISSUE TITLE
Version requirements and release

### ISSUE THREAD

**Issue by petschki** [plone/plone.recipe.zeoserver#46]
For the `3.0` release I wanted to set the required version of `zope.mkzeoinstance >=5.1.1` but then the tests are broken due to these constraints  https://dist.plone.org/release/6.0-dev/constraints.txt ... is there a way to override the constraint versions in the `tox.ini` ?

/cc @mauritsvanrees @gforcada

**Comment by gforcada** [comment]
not right away that I know of 😕

**Comment by mauritsvanrees** [comment]
We should create a way for that, maybe always have a `test-requirements.txt` and let tox install it, without using constraints.

But coredev 6.0 already pins `zope.mkzeoinstance` 5.1.1.  So I could also update the versions and constraints on 6.0-dev.
Done.  See also [release notes](https://dist.plone.org/release/6.0-dev/RELEASE-NOTES.md) and [changelog](https://dist.plone.org/release/6.0-dev/changelog.txt).

**Comment by petschki** [comment]
@mauritsvanrees I've updated the required versions. Could you make a 3.0.0 release?

**Comment by mauritsvanrees** [comment]
@petschki Done:
https://pypi.org/project/plone.recipe.zeoserver/3.0.0/

Thanks for fixing and pushing this!

**Comment by mauritsvanrees** [comment]
I have updated 6.0-dev with this version.
