### ISSUE TITLE
Tests fail with Error: Couldn't find a distribution for 'zope-interface>=5'.

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.recipe.zeoserver#52]
The tests on master fail, with as main problem: [`Error: Couldn't find a distribution for 'zope-interface>=5'.`](https://github.com/plone/plone.recipe.zeoserver/actions/runs/7874682464/job/21484868585#step:8:68). This is related to installing the `zrs` extra.  Problems start [here](https://github.com/plone/plone.recipe.zeoserver/blob/223702916faa254340b385c9618bd752f8891069/src/plone/recipe/zeoserver/tests/zeoserver.txt#L85-L100)

You can see it outside of the tests by using this buildout config:

```
[buildout]
parts = zeo

[zeo]
recipe = plone.recipe.zeoserver[zrs]
replicate-to = 127.0.0.1:5000
```

The `zope-interface>=5` comes from the `Twisted` dependency.  You can already see it going wrong with this even simpler buildout config:

```
[buildout]
parts = foobar

[foobar]
recipe = zc.recipe.egg
eggs = Twisted
```

You get:

```
$ bin/buildout 
root: Reading https://pypi.org/simple/zc.recipe.egg/
Updating foobar.
root: Reading https://pypi.org/simple/zope-interface/
Getting distribution for 'zope-interface>=5'.
While:
  Updating foobar.
  Getting distribution for 'zope-interface>=5'.
Error: Couldn't find a distribution for 'zope-interface>=5'.
```

The exact Python, pip or setuptools version does not seem to matter.

Adding this makes it work:

```
[versions]
Twisted = 22.10.0
```

But adding that in `zeoserver.txt` does not help.

We may want to remove these tests.  Last `zc.zrs` release was from 2017, and there has been some activity to get it compatible with ZODB 5.6+, but that never got released, and meanwhile the repository is archived: https://github.com/zopefoundation/zc.zrs

I myself am not using this.

**Comment by gforcada** [comment]
Sounds good 👍🏾
